- name: git checkout
  hosts: all

  tasks:
    - name: checkout
      ansible.builtin.git:
        repo: 'https://github.com/gourteacher/Assignment4CodeBase.git'
        dest: /srv/checkout

    - name: ensure repo exist
      ansible.builtin.git:
        repo: 'https://github.com/gourteacher/Assignment4CodeBase.git'
        dest: /srv/checkout
        update: no

    - name: get info from repo
      ansible.builtin.git:
        repo: 'https://foosball.example.org/path/to/repo.git'
        dest: /srv/checkout
        clone: no
        update: no

    #Install needed packages

    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest

    - name: start nginx
      service:
        name: nginx
        state: started

    - name: install python
      apt:
        name: python
        state: latest

    - name: install pip
      ansible.builtin.apt:
        name: python3-pip
        state: latest

    - name: install requirements
      ansible.builtin.pip:
        requirements: requirements.txt

    #Check if packages are installed

    - name: gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check if python is installed
      ansible.builtin.debug:
        msg: "Installed"
        when: "'python' in ansible_facts.packages"

    - name: Check if pip is installed
      ansible.builtin.debug:
        msg: "Installed"
        when: "'pip' in ansible_facts.packages"

#references
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_facts_module.html
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html